import { GoogleGenAI, Type } from "@google/genai";
import { Task, AIProvider } from '../types';

const geminiClient = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Mock OpenAI logic since we don't have a key provided in env
const mockOpenAIGenerate = async (systemInstruction: string, prompt: string): Promise<string> => {
  return new Promise((resolve) => {
    setTimeout(() => {
      // Simulate a response structure similar to what we expect
      resolve(JSON.stringify([
        {
          title: "OpenAI: Advanced Array Patterns",
          details: "Generated by ChatGPT. Focus on sliding window optimization techniques.",
          type: "Lecture",
          priority: "High",
          estimateMinutes: 45
        },
        {
          title: "OpenAI: 3 LeetCode Hard Problems",
          details: "Practice dynamic programming on grid problems.",
          type: "Practice",
          priority: "High",
          estimateMinutes: 90
        }
      ]));
    }, 2000);
  });
};

export const generateStudyPlan = async (
  currentTasks: Task[],
  provider: AIProvider,
  userPrompt?: string
): Promise<Partial<Task>[]> => {
  
  // Logic to determine context
  const codes = currentTasks.map(t => t.code).sort();
  const lastCode = codes[codes.length - 1] || 'P1D0';
  const match = lastCode.match(/P(\d+)D(\d+)/);
  let nextCode = 'P1D1';
  let phase = 'P1';
  let day = 'D1';

  if (match) {
    const p = parseInt(match[1]);
    const d = parseInt(match[2]);
    phase = `P${p}`;
    day = `D${d + 1}`;
    nextCode = `${phase}${day}`;
  }

  // --- MEMORY CONTEXT GENERATION ---
  // Extract completed task titles (last 20)
  const completedTasks = currentTasks
    .filter(t => t.status === 'Done')
    .map(t => t.title)
    .slice(-20);

  // Extract pending task titles (last 10)
  const pendingTasks = currentTasks
    .filter(t => t.status !== 'Done')
    .map(t => t.title)
    .slice(-10);

  const memoryContext = `
    CONTEXT AWARENESS:
    - The user has already COMPLETED these topics (Avoid repeating unless for revision): ${completedTasks.join('; ') || "None"}.
    - The user has these PENDING topics (Ensure continuity): ${pendingTasks.join('; ') || "None"}.
  `;
  // ---------------------------------

  const systemInstruction = `
    You are an expert Data Structures and Algorithms tutor. 
    Generate a study plan for the next day (${nextCode}).
    Current Phase: ${phase}.
    
    ${memoryContext}

    Return ONLY JSON array of task objects with fields: title, details, type, priority, estimateMinutes.
    Focus on: ${userPrompt || "Standard progression based on current phase"}.
  `;

  try {
    let responseText = "";

    if (provider === 'gemini') {
      const response = await geminiClient.models.generateContent({
        model: "gemini-2.5-flash",
        contents: `Generate tasks for ${nextCode}.`,
        config: {
          systemInstruction,
          responseMimeType: "application/json",
          responseSchema: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                title: { type: Type.STRING },
                details: { type: Type.STRING },
                type: { type: Type.STRING, enum: ['Lecture', 'Practice', 'Revision', 'Notes'] },
                priority: { type: Type.STRING, enum: ['High', 'Medium', 'Low'] },
                estimateMinutes: { type: Type.INTEGER },
              },
              required: ["title", "details", "type", "priority", "estimateMinutes"],
            },
          },
        },
      });
      responseText = response.text || "[]";
    } else {
      // ChatGPT provider
      responseText = await mockOpenAIGenerate(systemInstruction, `Generate tasks for ${nextCode}`);
    }

    const data = JSON.parse(responseText);
    return data.map((item: any) => ({
      ...item,
      phase,
      day,
      code: nextCode,
      status: 'Not started',
      isToday: false,
      actualMinutes: 0
    }));

  } catch (error) {
    console.error("AI generation failed:", error);
    throw error;
  }
};