
import { Task } from '../types';

export const createGoogleCalendarUrl = (task: Task) => {
  const title = encodeURIComponent(`DSA Study: ${task.title}`);
  const details = encodeURIComponent(`${task.details}\n\nType: ${task.type}\nPriority: ${task.priority}\n\nGenerated by DSA Master AI`);
  
  // Calculate dates
  // If task isToday, schedule it for the next hour or now. 
  // If not, we don't have a date picker in this MVP, so we default to Tomorrow 9AM or similar.
  // For better UX, let's assume "Today" means starting now or next round hour.
  
  const now = new Date();
  // Round to next hour
  now.setMinutes(0, 0, 0);
  now.setHours(now.getHours() + 1);
  
  const start = now.toISOString().replace(/-|:|\.\d\d\d/g, "");
  const end = new Date(now.getTime() + (task.estimateMinutes * 60000)).toISOString().replace(/-|:|\.\d\d\d/g, "");

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&dates=${start}/${end}`;
};

export const exportToNotionMarkdown = (tasks: Task[]) => {
  let md = `# DSA Study Plan Export\n\n`;
  
  tasks.forEach(t => {
    md += `## [${t.code}] ${t.title}\n`;
    md += `- **Status**: ${t.status}\n`;
    md += `- **Type**: ${t.type}\n`;
    md += `- **Time**: ${t.estimateMinutes}m est / ${t.actualMinutes}m actual\n`;
    md += `- **Details**: ${t.details}\n\n`;
    md += `---\n\n`;
  });

  return md;
};

export const requestNotificationPermission = async () => {
  if (!("Notification" in window)) {
    console.warn("This browser does not support desktop notification");
    return false;
  }
  
  if (Notification.permission === "granted") return true;
  
  if (Notification.permission !== "denied") {
    const permission = await Notification.requestPermission();
    return permission === "granted";
  }
  return false;
};

export const sendNotification = (title: string, body: string) => {
  if (!("Notification" in window)) return;
  
  if (Notification.permission === "granted") {
    // Try to find a valid icon or fallback
    // Note: In some browsers/OS, icon might not show up if path is invalid or local
    new Notification(title, { 
      body, 
      // Use a generic icon if available, otherwise browser default
      icon: '/vite.svg',
      tag: 'dsa-master-notification', // simple tagging to avoid stack up if needed
      renotify: true
    } as any);
  }
};
